/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/incidents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Incidents */
    get: operations['list_incidents_api_v1_incidents_get']
    put?: never
    /** Create Incident */
    post: operations['create_incident_api_v1_incidents_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/incidents/{incident_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Incident */
    get: operations['get_incident_api_v1_incidents__incident_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Incident */
    patch: operations['update_incident_api_v1_incidents__incident_id__patch']
    trace?: never
  }
  '/api/v1/incidents/{incident_id}/investigations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Investigations */
    get: operations['list_investigations_api_v1_incidents__incident_id__investigations_get']
    put?: never
    /** Create Investigation */
    post: operations['create_investigation_api_v1_incidents__incident_id__investigations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/investigations/{investigation_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Investigation */
    get: operations['get_investigation_api_v1_investigations__investigation_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/investigations/{investigation_id}/evidence': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Evidence */
    get: operations['list_evidence_api_v1_investigations__investigation_id__evidence_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/investigations/{investigation_id}/report': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Report */
    get: operations['get_report_api_v1_investigations__investigation_id__report_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/investigations/{investigation_id}/review': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Review */
    get: operations['get_review_api_v1_investigations__investigation_id__review_get']
    /**
     * Put Review
     * @description Create the single reviewer decision; exact retries return the same row.
     */
    put: operations['put_review_api_v1_investigations__investigation_id__review_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Root */
    get: operations['root__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Check */
    get: operations['health_check_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness */
    get: operations['readiness_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/inventory': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Inventory */
    get: operations['get_inventory_inventory_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** EvidenceLinkOut */
    EvidenceLinkOut: {
      /** Evidence Id */
      evidence_id: string
      /**
       * Relation
       * @enum {string}
       */
      relation: 'SUPPORTS' | 'CONTRADICTS'
    }
    /** EvidenceOut */
    EvidenceOut: {
      /** Id */
      id: string
      /** Investigation Id */
      investigation_id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'LOG' | 'TRACE' | 'METRIC' | 'CHANGE'
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string
      /** Service */
      service: string
      /** Summary */
      summary: string
      /** Source Backend */
      source_backend: string
      /** Source Ref */
      source_ref: string
      /** Trace Id */
      trace_id: string | null
      /**
       * Captured At
       * Format: date-time
       */
      captured_at: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HypothesisOut */
    HypothesisOut: {
      /** Id */
      id: string
      /** Explanation */
      explanation: string
      /**
       * Confidence
       * @enum {string}
       */
      confidence: 'LOW' | 'MEDIUM' | 'HIGH'
      /** Missing Evidence */
      missing_evidence: string[]
      /** Evidence */
      evidence: components['schemas']['EvidenceLinkOut'][]
    }
    /** IncidentCreate */
    IncidentCreate: {
      /** Title */
      title: string
      /**
       * Description
       * @default
       */
      description: string
      /** Service */
      service: string
      /**
       * Severity
       * @enum {string}
       */
      severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
      /**
       * Window Start
       * Format: date-time
       */
      window_start: string
      /**
       * Window End
       * Format: date-time
       */
      window_end: string
    }
    /** IncidentOut */
    IncidentOut: {
      /** Id */
      id: string
      /** Title */
      title: string
      /** Description */
      description: string
      /** Service */
      service: string
      /** Severity */
      severity: string
      /** Status */
      status: string
      /**
       * Window Start
       * Format: date-time
       */
      window_start: string
      /**
       * Window End
       * Format: date-time
       */
      window_end: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /** IncidentUpdate */
    IncidentUpdate: {
      /** Title */
      title?: string | null
      /** Description */
      description?: string | null
      /** Severity */
      severity?: ('LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL') | null
    }
    /** InvestigationCreate */
    InvestigationCreate: {
      /** Focus */
      focus?: string | null
    }
    /** InvestigationOut */
    InvestigationOut: {
      /** Id */
      id: string
      /** Incident Id */
      incident_id: string
      /** Parent Id */
      parent_id: string | null
      /** Status */
      status: string
      /** Focus */
      focus: string | null
      /**
       * Window Start
       * Format: date-time
       */
      window_start: string
      /**
       * Window End
       * Format: date-time
       */
      window_end: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Started At */
      started_at: string | null
      /** Finished At */
      finished_at: string | null
      /** Error */
      error: string | null
      job: components['schemas']['JobOut']
    }
    /** JobOut */
    JobOut: {
      /** Status */
      status: string
      /** Attempts */
      attempts: number
    }
    /** ReportOut */
    ReportOut: {
      /** Id */
      id: string
      /** Investigation Id */
      investigation_id: string
      /** Summary */
      summary: string
      /** Uncertainty */
      uncertainty: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Hypotheses */
      hypotheses: components['schemas']['HypothesisOut'][]
    }
    /** ReviewOut */
    ReviewOut: {
      /** Id */
      id: string
      /** Investigation Id */
      investigation_id: string
      /**
       * Decision
       * @enum {string}
       */
      decision: 'ACCEPTED' | 'REJECTED' | 'INCONCLUSIVE'
      /** Reviewer */
      reviewer: string
      /** Comment */
      comment: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** ReviewPut */
    ReviewPut: {
      /**
       * Decision
       * @enum {string}
       */
      decision: 'ACCEPTED' | 'REJECTED' | 'INCONCLUSIVE'
      /**
       * Comment
       * @default
       */
      comment: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_incidents_api_v1_incidents_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IncidentOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_incident_api_v1_incidents_post: {
    parameters: {
      query?: never
      header: {
        'Idempotency-Key': string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IncidentCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IncidentOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_incident_api_v1_incidents__incident_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        incident_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IncidentOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_incident_api_v1_incidents__incident_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        incident_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IncidentUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IncidentOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_investigations_api_v1_incidents__incident_id__investigations_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path: {
        incident_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvestigationOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_investigation_api_v1_incidents__incident_id__investigations_post: {
    parameters: {
      query?: never
      header: {
        'Idempotency-Key': string
      }
      path: {
        incident_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvestigationCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvestigationOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_investigation_api_v1_investigations__investigation_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        investigation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvestigationOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_evidence_api_v1_investigations__investigation_id__evidence_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path: {
        investigation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EvidenceOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_report_api_v1_investigations__investigation_id__report_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        investigation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReportOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_review_api_v1_investigations__investigation_id__review_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        investigation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_review_api_v1_investigations__investigation_id__review_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        investigation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewPut']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  root__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  health_check_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  readiness_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_inventory_inventory_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
